---
sudo: required
dist: trusty
before_install:
  - bash ./install_SDL2.sh
before_script:
  - "export DISPLAY=:99.0"
  - "export CXX=g++-4.8"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - bash ./test.sh
